version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: ex_doc
    versions:
    - 0.24.0
    - 0.24.1
